In [1]:
import pandas as pd
import numpy as np

In [2]:
file_name = 'H-2B_Cleaned_data.csv'
df = pd.read_csv(file_name)
print(df.shape)
df.head(10)

(6540, 22)

,CASE_STATUS,AGENT_POC_EMP_REP_BY_AGENT,SOC_CODE,NAICS_CODE,NBR_WORKERS_REQUESTED,FULL_TIME_POSITION,NATURE_OF_TEMPORARY_NEED,BASIC_NUMBER_OF_HOURS,BASIC_RATE_OF_PAY,SUPERVISE_HOW_MANY,...,EMP_EXP_NUM_MONTHS,WORKSITE_STATE,SWA_NAME,AGENT_ATTORNEY_CITY,WORKSITE_CITY,AGENT_ATTORNEY_STATE,HOURLY_WORK_SCHEDULE_AM,HOURLY_WORK_SCHEDULE_PM,OVERTIME_RATE_FROM,OVERTIME_RATE_TO
0,1,1,373011,5617,5,1,peakload,40.0,13.68,0.0,...,0.0,utah,0,brooklyn,sandy,new york,07:00:00,16:00:00,20.52,20.52
1,1,1,454011,115310,49,1,seasonal,36.0,14.27,0.0,...,0.0,arkansas,0,lake park,hermitage,georgia,06:00:00,13:00:00,21.41,22.50
2,1,1,352014,713930,3,1,peakload,40.0,15.12,0.0,...,12.0,florida,0,framingham,naples,massachusetts,09:00:00,17:00:00,22.68,22.68
3,1,1,373011,561730,10,1,seasonal,35.0,16.36,0.0,...,0.0,wyoming,0,charlottesville,teton village,virginia,05:00:00,13:00:00,24.54,24.54
4,1,1,372012,721110,12,1,peakload,35.0,12.66,0.0,...,6.0,vermont,0,framingham,west dover,massachusetts,08:00:00,15:00:00,18.99,18.99
5,1,1,454011,115310,35,1,seasonal,40.0,10.25,0.0,...,3.0,south carolina,0,coeur d' alene,saluda,idaho,08:00:00,17:00:00,15.38,21.29
6,1,1,452092,113210,16,1,seasonal,40.0,14.97,0.0,...,0.0,georgia,0,coeur d' alene,buena vista,idaho,07:00:00,17:00:00,22.46,22.46
7,1,1,373011,561730,20,1,seasonal,40.0,14.24,0.0,...,0.0,georgia,0,coeur d' alene,atlanta,idaho,08:00:00,17:00:00,21.36,21.36
8,1,1,454011,115310,60,1,seasonal,40.0,9.79,0.0,...,0.0,georgia,0,coeur d' alene,lagrange,idaho,08:00:00,16:00:00,14.69,29.67
9,1,0,372012,561720,20,1,seasonal,35.0,10.91,0.0,...,1.0,florida,0,no attorney representation,clearwater beach,no attorney representation,08:00:00,15:00:00,16.37,16.37

Let's do some feature engineering on the data. 
To start with, let's create some new features from existing features that might be useful in classifying cases as certified or denied.

- [STATE_MATCH]: WORKSITE_STATE matches AGENT_ATTORNEY_STATE.
- [CITY_MATCH]: WORKSITE_CITY matches AGENT_ATTORNEY_CITY.

In [10]:
# There has got to be a better way to do this...
df["STATE_MATCH"] = 0
df.loc[df["WORKSITE_STATE"] == df["AGENT_ATTORNEY_STATE"], "STATE_MATCH"] = 1
df.loc[df["WORKSITE_STATE"] != df["AGENT_ATTORNEY_STATE"], "STATE_MATCH"] = 0
# df.head()
# df["STATE_MATCH"].value_counts()

df["CITY_MATCH"] = 0
df.loc[df["WORKSITE_CITY"] == df["AGENT_ATTORNEY_CITY"], "CITY_MATCH"] = 1
df.loc[df["WORKSITE_CITY"] != df["AGENT_ATTORNEY_CITY"], "CITY_MATCH"] = 0
# df["CITY_MATCH"].value_counts()

# Maybe for analysis, match where statematch and citymatch are same value?

0    6322
1     218
Name: CITY_MATCH, dtype: int64